# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oTIFzLJ-uJs_ge7Exf54mM16J1ZTB4KX
"""

import streamlit as st
import math
import time

st.set_page_config(page_title="Kalkulator Koordinat Kartesius", layout="wide")

# Sidebar Menu
st.sidebar.title("🔧 Menu Navigasi")
menu = st.sidebar.radio("Pilih Menu", ["📖 Panduan", "📍 Kalkulator Koordinat", "🎯 Tujuan Pembelajaran"])

# Halaman Panduan
if menu == "📖 Panduan":
    st.title("📖 Panduan Penggunaan")
    with st.expander("Lihat Petunjuk Lengkap"):
        st.write("""
        Selamat datang di Aplikasi Kalkulator Koordinat Kartesius!

        *Fitur:*
        - Hitung Jarak antara 2 titik di bidang koordinat.
        - Hitung Kemiringan garis yang menghubungkan kedua titik.

        *Langkah-langkah:*
        1️⃣ Pilih menu 'Kalkulator Koordinat'.
        2️⃣ Masukkan koordinat (X1, Y1) dan (X2, Y2).
        3️⃣ Klik tombol Hitung, tunggu proses selesai.
        4️⃣ Lihat hasil jarak dan kemiringan yang tampil.

        *Catatan:*
        Untuk garis vertikal, kemiringan dianggap Tak Hingga.
        """)
if st.button("🚀 Hitung Jarak & Kemiringan"):
    with st.spinner("Sedang menghitung..."):
        time.sleep(1)

        jarak = math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)

        if x2 - x1 != 0:
            kemiringan = (y2 - y1) / (x2 - x1)
            kemiringan_text = f"{kemiringan:.2f}"
        else:
            kemiringan_text = "Tak Hingga (Garis Vertikal)"

        st.success("✅ Perhitungan Selesai!")
        st.metric("Jarak antara dua titik", f"{jarak:.2f}")
        st.metric("Kemiringan garis", kemiringan_text)

        # --- Visualisasi Titik dan Garis ---
        import matplotlib.pyplot as plt
        fig, ax = plt.subplots()
        ax.plot([x1, x2], [y1, y2], marker='o', color='blue', linestyle='-')
        ax.text(x1, y1, f'  A({x1}, {y1})', fontsize=10, verticalalignment='bottom')
        ax.text(x2, y2, f'  B({x2}, {y2})', fontsize=10, verticalalignment='bottom')
        ax.grid(True)
        ax.axhline(0, color='black', linewidth=1)
        ax.axvline(0, color='black', linewidth=1)
        ax.set_xlabel("X")
        ax.set_ylabel("Y")
        ax.set_title("Visualisasi Titik dan Garis Koordinat Kartesius")
        st.pyplot(fig)


# Halaman Tujuan Pembelajaran
elif menu == "🎯 Tujuan Pembelajaran":
    st.title("🎯 Tujuan Pembelajaran")
    st.write("""
    Dengan aplikasi Kalkulator Koordinat Kartesius ini, pengguna diharapkan mampu:

    ✅ Memahami konsep sistem koordinat Kartesius.
    ✅ Menentukan jarak antara dua titik di bidang koordinat.
    ✅ Menghitung kemiringan atau gradien garis penghubung dua titik.
    ✅ Mengembangkan kemampuan analisis geometri dasar.
    ✅ Memanfaatkan teknologi untuk membantu perhitungan matematis.

    Aplikasi ini sangat cocok digunakan oleh:
    - Pelajar sekolah menengah
    - Mahasiswa tingkat dasar
    - Guru sebagai media bantu pembelajaran interaktif
    """)
